### ISSUE TITLE
Почему бы не использовать `pydantic.BaseSettings`?

### ISSUE THREAD

**Issue by ghost** [nomilkinmyhome/vkbottle_bot_architecture_example#11]
Почему бы не использовать `pydantic.BaseSettings` вместо `config.py`?

**Comment by nomilkinmyhome** [comment]
А в чем плюс? По-моему и так норм

**Comment by ghost** [comment]
@nomilkinmyhome Кода меньше да и в целом удобнее имхо. `BaseSettings` специально для этого и делали

**Comment by Ne0shka** [comment]
> @nomilkinmyhome Кода меньше да и в целом удобнее имхо. `BaseSettings` специально для этого и делали

Если в проекте `pydantic` будет использован - то да, вполне, но если нет, то тянуть его только ради `BaseSettings` - бредовая идея имхо

**Comment by ghost** [comment]
@Ne0shka Бесспорно. Но в данной конкретной ситуации `pydantic` уже есть в зависимостях, поэтому я и предложил)

**Comment by nomilkinmyhome** [comment]
@vanburgerberg если есть желание, то можешь сделать пр
