### ISSUE TITLE
Авторелоад работает некорректно

### ISSUE THREAD

**Issue by Ne0shka** [nomilkinmyhome/vkbottle_bot_architecture_example#3]
При включенном auto_reload в LoopWrapper бот перезапускается некорректно:
![image](https://user-images.githubusercontent.com/37632288/106490043-d84e9000-64ce-11eb-8b43-7ca5ddf9d593.png)
Предположительно, авторелоад пытается запуститься через python __main__.py вместо python -m src.
![image](https://user-images.githubusercontent.com/37632288/106490200-0502a780-64cf-11eb-8261-bddb3d164ce7.png)

**Comment by Ne0shka** [comment]
Сам авторелоад: https://github.com/timoniq/vkbottle/blob/master/vkbottle/tools/dev_tools/auto_reload.py

**Comment by nomilkinmyhome** [comment]
Справедливо только для винды или на линуксе также?

**Comment by Ne0shka** [comment]
> Справедливо только для винды или на линуксе также?

На линуксе пока не пробовал, сегодня-завтра проверю

**Comment by qpyparty** [comment]
итак, появилось какое-нибудь решение такой проблемы?
